version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_UESR: postgres
      POSTGRES_PASSWORD: ssafy
      POSTGRES_DB: ddada
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    name: ddada-network
    external: true

volumes:
  db-data: {}
  
