global:
  scrape_interval: 15s
  evaluation_interval: 15s

# scheme defaults to 'http'
# metrics_path defaults to '/metrics'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [localhost:9090]

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ddada-be:8081']
      
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres_exporter:9187']
      
  - job_name: 'elasticsearch'
    scrape_interval: 5s
    static_configs:
      - targets: ['elasticsearch_exporter:9114']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']

