version: '3.8'

services:
  backend:
    image: jounghs3933/ddada-be:0.1.0
    container_name: ddada-be
    env_file:
      - .env
    ports:
      - 8080:8080
      - 8081:8081

networks:
  default:
    name: ddada-network
    external: true
